server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never

spring:
  application:
    name: GATEWAY-SERVICE

zuul:
  routes:
    user-service:
      path: /users/**
      #url: http://localhost:8081/users/
      url: https://user.the-capacity.com/users/
      sensitiveHeaders: Cookie,Set-Cookie,Authorization,Auth-Token
    #email:
    #  path: /email/**
    #  url: http://localhost:8082/email/



# For Register with eureka server as a client
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #default-time-zone: http://localhost:8761/eureka
      defaultZone: https://admin:irb1234@discovery.the-capacity.com/eureka
      #defaultZone: http://admin:irb1234@localhost:8761/eureka